import Head from "next/head";
import Product from "../components/product";
import styled from "styled-components";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";

export default function Home() {
  const [result] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = result;

  if (fetching) {
    return <p>...Loading</p>;
  }
  if (error) {
    return <p>Fetch Error</p>;
  }
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Studio Kursi</h1>
        <Gallery>
          {products.map((product) => {
            return <Product product={product} />;
          })}
        </Gallery>
      </main>
    </div>
  );
}

const Gallery = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(20rem, 1fr));
`;
